power: implement the new node ceiling methods
  frameworks/native/libs/binder/ndk/include_cpp/android/
    binder_interface_utils.h:104:20: error: allocating an object of
    abstract class type '...impl::example::Power'
  hardware/interfaces/power/aidl/default/main.cpp:27:54: note:
    in instantiation of function template specialization
    'ndk::SharedRefBase::make<...Power>' requested here
   27 |     std::shared_ptr<Power> vib = ndk::SharedRefBase::make<Power>();
  out/.../IPower.h:95:32: note: unimplemented pure virtual method
    'setNodeCeiling' in 'Power'
  out/.../IPower.h:96:32: note: unimplemented pure virtual method
    'clearNodeCeiling' in 'Power'

IPower V6 added setNodeCeiling and clearNodeCeiling, so the example HAL
is abstract. Both are no-ops, matching how the neighbouring
sendComposition methods handle what the example does not model.

hardware/interfaces is an AxionOS fork, so 15-ours. Counts now twelve.

206 patches, 0 conflicts.